"""Add rows, cols, mines, board to Game model

Revision ID: 5acf4a30970f
Revises: 6977ccd3fc2a
Create Date: 2025-10-05 15:18:32.779417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5acf4a30970f'
down_revision = '6977ccd3fc2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rows', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('cols', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('mines', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('board', sa.Text(), nullable=False))
        batch_op.drop_column('board_state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('board_state', sa.TEXT(), nullable=False))
        batch_op.drop_column('board')
        batch_op.drop_column('mines')
        batch_op.drop_column('cols')
        batch_op.drop_column('rows')

    # ### end Alembic commands ###
